version: '3.8'

services:
  backend:
    image: ghcr.io/team-3-ynov/ynov-secret-santa-back-end:production
    environment:
      - NODE_ENV=production
    command: sh -c "node dist/scripts/seed-production.js 2>/dev/null || true && node dist/index.js"

  postgres:
    ports: []
